inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - test/**/*.rb

Style/HashEachMethods:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": ()

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma # NOTE this matches the Jenkins p/r builder that uses Foodcritic

Style/SignalException:
  Enabled: false
